version: '2'
services:
  data:
    build: docker/jenkins-data
  master:
    build: docker/jenkins-master
    volumes_from:
      - data
    volumes:
      - ./jenkinslocation.txt:/myfiles/jenkinslocation.txt
    ports:
      - "50000:50000"
  nginx:
    build: docker/jenkins-nginx
    ports:
      - "80:80"
    links:
      - master:jenkins-master
  slave:
    build: docker/jenkins-slave
  proxy:
    build: docker/jenkins-proxy
    command: -i
    ports:
      - "3375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

